//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVM_Refregator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVVM_Refregator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [
        ///  {
        ///    &quot;Food Group&quot;: 1,
        ///    &quot;Item No.&quot;: 1001,
        ///    &quot;Index No.&quot;: 1,
        ///    &quot;Food and Description&quot;: &quot;アマランサス　玄穀　&quot;,
        ///    &quot;Refuse&quot;: 0.0,
        ///    &quot;Energy (kcal)&quot;: 358.0,
        ///    &quot;Energy (kJ)&quot;: 1498.0,
        ///    &quot;Water&quot;: 13.5,
        ///    &quot;Protein, calculated from  reference nitrogen&quot;: 12.7,
        ///    &quot;Protein, calculated as  the sum of amino acid residues&quot;: 12.5,
        ///    &quot;Lipid&quot;: 6.0,
        ///    &quot;Fatty acid, triacyl-glycerol equivalents&quot;: 5.0,
        ///    &quot;Fatty acid, saturated&quot;: 1.18,
        ///    &quot;Fatty acid, mono-unsaturated&quot;: 1.48,
        ///    &quot;Fatty acid, p [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string food_composition_japanese {
            get {
                return ResourceManager.GetString("food_composition_japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///    - LiveCharts
        /// - LiveCharts.Wpf
        ///
        ///The MIT License (MIT)
        ///
        ///Copyright (c) 2016 Alberto Rodriguez &amp; LiveCharts contributors
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furn [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
    }
}
